# Server
server.port=8080


spring.datasource.url=jdbc:postgresql://dpg-d91mv9rtqb8s739bi5tg-a.singapore-postgres.render.com:5432/wms_b926
spring.datasource.username=wms_user
spring.datasource.password=NHEvHyC2RdUQV8knjVjEGMQALlv7qeEG
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=warehouse-secret-key-techit-2026-must-be-256-bits-long
jwt.expiration=2592000000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=345698897037-cd75gdpirddonk5b3bjife220fo4gdkc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Frontend URL
frontend.url=https://my-warehouse-frontend.netlify.app

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Fix Circular Dependency
spring.main.allow-circular-references=true